### ISSUE TITLE
源疑似失效

### ISSUE THREAD

**Issue by zhou1012** [jeffreymor/GoogleHosts#2]
检查hosts已经更改，可完全没起作用，疑似源失效

**Comment by jeffreymor** [comment]
这个我也没办法。。维护hosts源的也说了现在ip和谐的很快，而他更新频率也是越来越低了，现在只靠hosts出墙也不太现实（有个ipv6版本的hosts效果不错，但是我这边的手机网络连不上ipv6地址），建议有硬性需求的还是自建梯子用吧
